// Dynamic classes added here so they are compiled into the CSS
const backgrounds = {
  normal: 'bg-type-normal',
  fire: 'bg-type-fire',
  water: 'bg-type-water',
  grass: 'bg-type-grass',
  electric: 'bg-type-electric',
  ice: 'bg-type-ice',
  fighting: 'bg-type-fighting',
  poison: 'bg-type-poison',
  ground: 'bg-type-ground',
  flying: 'bg-type-flying',
  psychic: 'bg-type-psychic',
  bug: 'bg-type-bug',
  rock: 'bg-type-rock',
  ghost: 'bg-type-ghost',
  dark: 'bg-type-dark',
  dragon: 'bg-type-dragon',
  steel: 'bg-type-steel',
  fairy: 'bg-type-fairy'
}
const backgroundsLight = {
  normal: 'bg-type-normal-light',
  fire: 'bg-type-fire-light',
  water: 'bg-type-water-light',
  grass: 'bg-type-grass-light',
  electric: 'bg-type-electric-light',
  ice: 'bg-type-ice-light',
  fighting: 'bg-type-fighting-light',
  poison: 'bg-type-poison-light',
  ground: 'bg-type-ground-light',
  flying: 'bg-type-flying-light',
  psychic: 'bg-type-psychic-light',
  bug: 'bg-type-bug-light',
  rock: 'bg-type-rock-light',
  ghost: 'bg-type-ghost-light',
  dark: 'bg-type-dark-light',
  dragon: 'bg-type-dragon-light',
  steel: 'bg-type-steel-light',
  fairy: 'bg-type-fairy-light'
}
const backgroundsDark = {
  normal: 'bg-type-normal-dark',
  fire: 'bg-type-fire-dark',
  water: 'bg-type-water-dark',
  grass: 'bg-type-grass-dark',
  electric: 'bg-type-electric-dark',
  ice: 'bg-type-ice-dark',
  fighting: 'bg-type-fighting-dark',
  poison: 'bg-type-poison-dark',
  ground: 'bg-type-ground-dark',
  flying: 'bg-type-flying-dark',
  psychic: 'bg-type-psychic-dark',
  bug: 'bg-type-bug-dark',
  rock: 'bg-type-rock-dark',
  ghost: 'bg-type-ghost-dark',
  dark: 'bg-type-dark-dark',
  dragon: 'bg-type-dragon-dark',
  steel: 'bg-type-steel-dark',
  fairy: 'bg-type-fairy-dark'
}
const borders = {
  normal: 'border-type-normal',
  fire: 'border-type-fire',
  water: 'border-type-water',
  grass: 'border-type-grass',
  electric: 'border-type-electric',
  ice: 'border-type-ice',
  fighting: 'border-type-fighting',
  poison: 'border-type-poison',
  ground: 'border-type-ground',
  flying: 'border-type-flying',
  psychic: 'border-type-psychic',
  bug: 'border-type-bug',
  rock: 'border-type-rock',
  ghost: 'border-type-ghost',
  dark: 'border-type-dark',
  dragon: 'border-type-dragon',
  steel: 'border-type-steel',
  fairy: 'border-type-fairy'
}

const gradientFrom = {
  normal: 'from-type-normal',
  fire: 'from-type-fire',
  water: 'from-type-water',
  grass: 'from-type-grass',
  electric: 'from-type-electric',
  ice: 'from-type-ice',
  fighting: 'from-type-fighting',
  poison: 'from-type-poison',
  ground: 'from-type-ground',
  flying: 'from-type-flying',
  psychic: 'from-type-psychic',
  bug: 'from-type-bug',
  rock: 'from-type-rock',
  ghost: 'from-type-ghost',
  dark: 'from-type-dark',
  dragon: 'from-type-dragon',
  steel: 'from-type-steel',
  fairy: 'from-type-fairy'
}
const gradientFromLight = {
  normal: 'from-type-normal-light',
  fire: 'from-type-fire-light',
  water: 'from-type-water-light',
  grass: 'from-type-grass-light',
  electric: 'from-type-electric-light',
  ice: 'from-type-ice-light',
  fighting: 'from-type-fighting-light',
  poison: 'from-type-poison-light',
  ground: 'from-type-ground-light',
  flying: 'from-type-flying-light',
  psychic: 'from-type-psychic-light',
  bug: 'from-type-bug-light',
  rock: 'from-type-rock-light',
  ghost: 'from-type-ghost-light',
  dark: 'from-type-dark-light',
  dragon: 'from-type-dragon-light',
  steel: 'from-type-steel-light',
  fairy: 'from-type-fairy-light'
}
const gradientFromDark = {
  normal: 'from-type-normal-dark',
  fire: 'from-type-fire-dark',
  water: 'from-type-water-dark',
  grass: 'from-type-grass-dark',
  electric: 'from-type-electric-dark',
  ice: 'from-type-ice-dark',
  fighting: 'from-type-fighting-dark',
  poison: 'from-type-poison-dark',
  ground: 'from-type-ground-dark',
  flying: 'from-type-flying-dark',
  psychic: 'from-type-psychic-dark',
  bug: 'from-type-bug-dark',
  rock: 'from-type-rock-dark',
  ghost: 'from-type-ghost-dark',
  dark: 'from-type-dark-dark',
  dragon: 'from-type-dragon-dark',
  steel: 'from-type-steel-dark',
  fairy: 'from-type-fairy-dark'
}
const gradientTo = {
  normal: 'to-type-normal',
  fire: 'to-type-fire',
  water: 'to-type-water',
  grass: 'to-type-grass',
  electric: 'to-type-electric',
  ice: 'to-type-ice',
  fighting: 'to-type-fighting',
  poison: 'to-type-poison',
  ground: 'to-type-ground',
  flying: 'to-type-flying',
  psychic: 'to-type-psychic',
  bug: 'to-type-bug',
  rock: 'to-type-rock',
  ghost: 'to-type-ghost',
  dark: 'to-type-dark',
  dragon: 'to-type-dragon',
  steel: 'to-type-steel',
  fairy: 'to-type-fairy'
}
const gradientToLight = {
  normal: 'to-type-normal-light',
  fire: 'to-type-fire-light',
  water: 'to-type-water-light',
  grass: 'to-type-grass-light',
  electric: 'to-type-electric-light',
  ice: 'to-type-ice-light',
  fighting: 'to-type-fighting-light',
  poison: 'to-type-poison-light',
  ground: 'to-type-ground-light',
  flying: 'to-type-flying-light',
  psychic: 'to-type-psychic-light',
  bug: 'to-type-bug-light',
  rock: 'to-type-rock-light',
  ghost: 'to-type-ghost-light',
  dark: 'to-type-dark-light',
  dragon: 'to-type-dragon-light',
  steel: 'to-type-steel-light',
  fairy: 'to-type-fairy-light'
}
const gradientToDark = {
  normal: 'to-type-normal-dark',
  fire: 'to-type-fire-dark',
  water: 'to-type-water-dark',
  grass: 'to-type-grass-dark',
  electric: 'to-type-electric-dark',
  ice: 'to-type-ice-dark',
  fighting: 'to-type-fighting-dark',
  poison: 'to-type-poison-dark',
  ground: 'to-type-ground-dark',
  flying: 'to-type-flying-dark',
  psychic: 'to-type-psychic-dark',
  bug: 'to-type-bug-dark',
  rock: 'to-type-rock-dark',
  ghost: 'to-type-ghost-dark',
  dark: 'to-type-dark-dark',
  dragon: 'to-type-dragon-dark',
  steel: 'to-type-steel-dark',
  fairy: 'to-type-fairy-dark'
}
const gradientVia = {
  normal: 'via-type-normal',
  fire: 'via-type-fire',
  water: 'via-type-water',
  grass: 'via-type-grass',
  electric: 'via-type-electric',
  ice: 'via-type-ice',
  fighting: 'via-type-fighting',
  poison: 'via-type-poison',
  ground: 'via-type-ground',
  flying: 'via-type-flying',
  psychic: 'via-type-psychic',
  bug: 'via-type-bug',
  rock: 'via-type-rock',
  ghost: 'via-type-ghost',
  dark: 'via-type-dark',
  dragon: 'via-type-dragon',
  steel: 'via-type-steel',
  fairy: 'via-type-fairy'
}
const gradientViaLight = {
  normal: 'via-type-normal-light',
  fire: 'via-type-fire-light',
  water: 'via-type-water-light',
  grass: 'via-type-grass-light',
  electric: 'via-type-electric-light',
  ice: 'via-type-ice-light',
  fighting: 'via-type-fighting-light',
  poison: 'via-type-poison-light',
  ground: 'via-type-ground-light',
  flying: 'via-type-flying-light',
  psychic: 'via-type-psychic-light',
  bug: 'via-type-bug-light',
  rock: 'via-type-rock-light',
  ghost: 'via-type-ghost-light',
  dark: 'via-type-dark-light',
  dragon: 'via-type-dragon-light',
  steel: 'via-type-steel-light',
  fairy: 'via-type-fairy-light'
}
const gradientViaDark = {
  normal: 'via-type-normal-dark',
  fire: 'via-type-fire-dark',
  water: 'via-type-water-dark',
  grass: 'via-type-grass-dark',
  electric: 'via-type-electric-dark',
  ice: 'via-type-ice-dark',
  fighting: 'via-type-fighting-dark',
  poison: 'via-type-poison-dark',
  ground: 'via-type-ground-dark',
  flying: 'via-type-flying-dark',
  psychic: 'via-type-psychic-dark',
  bug: 'via-type-bug-dark',
  rock: 'via-type-rock-dark',
  ghost: 'via-type-ghost-dark',
  dark: 'via-type-dark-dark',
  dragon: 'via-type-dragon-dark',
  steel: 'via-type-steel-dark',
  fairy: 'via-type-fairy-dark'
}